import { Project } from '@/types/project';

export const projectsData: Project[] = [
  // Fundamentals (1-10)
  {
    id: 'project-001',
    day: 1,
    title: 'To-Do List App',
    description: 'Temel CRUD işlemleri ile görev yönetimi uygulaması',
    category: 'fundamentals',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    difficulty: 'beginner',
    skills: ['DOM manipülasyonu', 'localStorage', 'Event handling'],
    status: 'completed',
  },
  {
    id: 'project-002',
    day: 2,
    title: 'Calculator App',
    description: 'Temel matematiksel işlemleri yapan hesap makinesi',
    category: 'fundamentals',
    technologies: ['JavaScript', 'CSS', 'TypeScript'],
    difficulty: 'beginner',
    skills: [
      'Event handling',
      'State management',
      'Error handling',
      'CSS Grid layout',
    ],
    status: 'completed',
  },
  {
    id: 'project-003',
    day: 3,
    title: 'Weather App',
    description: 'OpenWeatherMap API ile hava durumu ve 5 günlük tahmin',
    category: 'fundamentals',
    technologies: ['React', 'API', 'TypeScript'],
    difficulty: 'intermediate',
    skills: [
      'API integration',
      'Fetch & async/await',
      'Geolocation API',
      'Error handling',
      'Loading states',
      'Conditional rendering',
      'Date formatting',
    ],
    status: 'in-progress',
  },
  {
    id: 'project-004',
    day: 4,
    title: 'Clock & Timer App',
    description: 'Dijital saat, zamanlayıcı ve kronometre özellikleri',
    category: 'fundamentals',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    difficulty: 'beginner',
    skills: ['Date API', 'setInterval', 'clearInterval', 'Time formatting'],
    status: 'not-started',
  },
  {
    id: 'project-005',
    day: 5,
    title: 'Random Quote Generator',
    description: 'API kullanarak rastgele ilham verici alıntılar gösterme',
    category: 'fundamentals',
    technologies: ['JavaScript', 'API'],
    difficulty: 'beginner',
    skills: [
      'Fetch API',
      'DOM manipülasyonu',
      'Event handling',
      'API tüketimi',
    ],
    status: 'not-started',
  },
  {
    id: 'project-006',
    day: 6,
    title: 'QR Code Generator',
    description: "Text veya URL'den QR kod oluşturma uygulaması",
    category: 'fundamentals',
    technologies: ['JavaScript', 'API'],
    difficulty: 'beginner',
    skills: ['3rd party API', 'Image handling', 'Download functionality'],
    status: 'not-started',
  },
  {
    id: 'project-007',
    day: 7,
    title: 'Markdown Editor',
    description: 'Canlı önizleme ile markdown editörü',
    category: 'fundamentals',
    technologies: ['JavaScript', 'React'],
    difficulty: 'intermediate',
    skills: [
      'Markdown parsing',
      'Live preview',
      'Textarea handling',
      'State management',
    ],
    status: 'not-started',
  },
  {
    id: 'project-008',
    day: 8,
    title: 'Unit Converter App',
    description: 'Uzunluk, ağırlık, sıcaklık dönüştürme uygulaması',
    category: 'fundamentals',
    technologies: ['JavaScript'],
    difficulty: 'beginner',
    skills: ['Matematiksel dönüşümler', 'Form handling', 'Validation'],
    status: 'not-started',
  },
  {
    id: 'project-009',
    day: 9,
    title: 'Typing Speed Test',
    description: 'WPM (words per minute) hesaplayan yazma hızı testi',
    category: 'fundamentals',
    technologies: ['JavaScript', 'TypeScript'],
    difficulty: 'intermediate',
    skills: [
      'Timer logic',
      'Input tracking',
      'Accuracy calculation',
      'Real-time stats',
    ],
    status: 'not-started',
  },
  {
    id: 'project-010',
    day: 10,
    title: 'Image Carousel',
    description: 'Manuel ve otomatik kaydırmalı resim galerisi',
    category: 'fundamentals',
    technologies: ['JavaScript', 'CSS'],
    difficulty: 'beginner',
    skills: [
      'DOM manipulation',
      'CSS transitions',
      'Timer',
      'Navigation logic',
    ],
    status: 'not-started',
  },
  {
    id: 'project-011',
    day: 11,
    title: 'Responsive Navigation Bar',
    description: 'Mobil uyumlu hamburger menülü, sticky navigasyon çubuğu',
    category: 'css-ui',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    difficulty: 'beginner',
    skills: [
      'Flexbox layout',
      'Media queries',
      'Hamburger menu animasyonu',
      'Sticky navigation',
      'Responsive design',
      'CSS transitions',
    ],
    status: 'not-started',
  },
  {
    id: 'project-012',
    day: 12,
    title: 'Accordion UI Component',
    description: 'Açılır-kapanır accordion/collapse component',
    category: 'css-ui',
    technologies: ['React', 'CSS', 'JavaScript'],
    difficulty: 'beginner',
    skills: [
      'State management',
      'Conditional rendering',
      'CSS animations',
      'Event handling',
      'Component composition',
    ],
    status: 'not-started',
  },
  {
    id: 'project-013',
    day: 13,
    title: 'Modal Component',
    description: 'Overlay ile çalışan modal/dialog penceresi',
    category: 'css-ui',
    technologies: ['React', 'CSS'],
    difficulty: 'beginner',
    skills: [
      'React Portal',
      'Focus trap',
      'Overlay backdrop',
      'ESC key handling',
      'Body scroll lock',
      'Accessibility (ARIA)',
      'Portal API',
    ],
    status: 'not-started',
  },
  {
    id: 'project-014',
    day: 14,
    title: 'Tooltip Component',
    description: 'Hover ve focus olaylarında açılan tooltip bileşeni',
    category: 'css-ui',
    technologies: ['React', 'CSS', 'JavaScript'],
    difficulty: 'beginner',
    skills: [
      'Positioning (absolute)',
      'Event listeners',
      'Dynamic content',
      'CSS animations',
      'Hover states',
    ],
    status: 'not-started',
  },
  {
    id: 'project-015',
    day: 15,
    title: 'CSS Animations Showcase',
    description: 'Çeşitli CSS animasyonları ve transition örnekleri',
    category: 'css-ui',
    technologies: ['CSS', 'HTML'],
    difficulty: 'beginner',
    skills: [
      'CSS keyframes',
      'Animation properties',
      'Transform',
      'Transition timing',
      'Easing functions',
    ],
    status: 'not-started',
  },
  {
    id: 'project-016',
    day: 16,
    title: 'Image Hover Effects Gallery',
    description: 'Görsel hover efektleri ile interaktif galeri',
    category: 'css-ui',
    technologies: ['CSS', 'HTML'],
    difficulty: 'beginner',
    skills: [
      'CSS Grid',
      'Hover effects',
      'Overlay effects',
      'Transform & scale',
      'Image optimization',
    ],
    status: 'not-started',
  },
  {
    id: 'project-017',
    day: 17,
    title: 'Skeleton Loader Animation',
    description: 'İçerik yüklenirken gösterilen iskelet yükleyici',
    category: 'css-ui',
    technologies: ['CSS', 'React'],
    difficulty: 'beginner',
    skills: [
      'Shimmer animation',
      'Loading states',
      'CSS gradients',
      'Pulse effects',
      'Component patterns',
    ],
    status: 'not-started',
  },
  {
    id: 'project-018',
    day: 18,
    title: 'Custom 404 Page Design',
    description: 'Yaratıcı ve kullanıcı dostu 404 hata sayfası',
    category: 'css-ui',
    technologies: ['Next.js', 'CSS', 'React'],
    difficulty: 'beginner',
    skills: [
      'Error pages',
      'Creative design',
      'Animations',
      'Navigation',
      'User experience',
    ],
    status: 'not-started',
  },
  {
    id: 'project-019',
    day: 19,
    title: 'Responsive Landing Page',
    description: 'Modern ve responsive tek sayfalık landing page',
    category: 'css-ui',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    difficulty: 'intermediate',
    skills: [
      'Responsive layout',
      'Hero section',
      'Grid & Flexbox',
      'Media queries',
      'Call-to-action design',
      'Mobile-first approach',
    ],
    status: 'not-started',
  },
  {
    id: 'project-020',
    day: 20,
    title: 'Mobile-first Blog Layout',
    description: 'Mobil öncelikli blog sayfa düzeni',
    category: 'css-ui',
    technologies: ['CSS', 'HTML'],
    difficulty: 'intermediate',
    skills: [
      'CSS Grid',
      'Mobile-first design',
      'Typography',
      'Reading experience',
      'Sidebar layout',
      'Grid layout',
      'Responsive images',
    ],
    status: 'not-started',
  },

  // ... (diğer 97 proje buraya eklenecek)
];

// Kategori bazlı filtreleme
export const getProjectsByCategory = (category: string) => {
  return projectsData.filter(project => project.category === category);
};

// ID'ye göre proje getir
export const getProjectById = (id: string) => {
  return projectsData.find(project => project.id === id);
};

// Durum bazlı filtreleme
export const getProjectsByStatus = (status: string) => {
  return projectsData.filter(project => project.status === status);
};
